# Site settings
title: portfolYOU
description: >
  Lorem ipsum dolor sit amet, his eu liber nobis senserit,
  ne option debitis adipiscing duo, has in eirmod ancillae.
baseurl: "/portfolYOU"

# Author Info
author:
  name:
  email:
  github:
  twitter:
  linkedin:
  facebook: