# Site settings
title: portfolYOU
description: >
  Lorem ipsum dolor sit amet, his eu liber nobis senserit,
  ne option debitis adipiscing duo, has in eirmod ancillae.
baseurl: "/portfolYOU/"
repo_url: https://github.com/YoussefRaafatNasry/portfolYOU

# Posts Permalink
permalink: articles/:title

# Author Info
author:
  img: https://ssl.gstatic.com/images/branding/product/1x/avatar_square_blue_512dp.png
  name: John Doe
  email: portfolYOU@xyz.com
  github: portfolYOU
  twitter: portfolYOU
  linkedin: portfolYOU
  facebook: portfolYOU