# Site settings
title: portfolYOU
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, his eu liber nobis senserit,
  ne option debitis adipiscing duo, has in eirmod ancillae.
baseurl: "/portfolYOU"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : John Doe
  image    : https://ssl.gstatic.com/images/branding/product/1x/avatar_square_blue_512dp.png
  email    : portfolYOU@xyz.com
  github   : portfolYOU
  twitter  : portfolYOU
  linkedin : portfolYOU
  facebook : portfolYOU


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock