### Site Settings ###
baseurl             : "/portfolYOU-dev"
repository          : YoussefRaafatNasry/portfolYOU
theme               : portfolyou-jekyll-theme


### Navbar Settings ###
nav_exclude:
  - blog/tags.html
  - blog/page-:num/index.html
  - pages/404.html
  - pages/index.md
  - pages/documentation/**


### Author Info ###
author:
  name              : YRN
  image             : https://avatars2.githubusercontent.com/u/41103290
  github            : YoussefRaafatNasry


### Posts ###
paginate: 6
paginate_path: "/blog/page-:num/"
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
